-- NextGenTechBD D1 seed data (auto-generated from products.json / settings.json)

DELETE FROM categories;
INSERT INTO categories (id,name,name_en,e,img) VALUES ('e', 'ইলেকট্রনিক্স', NULL, '📱', NULL);
INSERT INTO categories (id,name,name_en,e,img) VALUES ('f', 'ফ্যাশন', NULL, '👗', NULL);
INSERT INTO categories (id,name,name_en,e,img) VALUES ('h', 'হোম ও লিভিং', NULL, '🏠', NULL);
INSERT INTO categories (id,name,name_en,e,img) VALUES ('b', 'বিউটি ও হেলথ', NULL, '💄', NULL);
INSERT INTO categories (id,name,name_en,e,img) VALUES ('g', 'গ্রোসারি', NULL, '🛒', NULL);
INSERT INTO categories (id,name,name_en,e,img) VALUES ('t', 'বেবি ও খেলনা', NULL, '🧸', NULL);
INSERT INTO categories (id,name,name_en,e,img) VALUES ('s', 'স্পোর্টস', NULL, '⚽', NULL);
INSERT INTO categories (id,name,name_en,e,img) VALUES ('k', 'বই ও স্টেশনারি', NULL, '📚', NULL);

DELETE FROM products;
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (1, 'e', 'স্মার্টফোন Nova X15 Pro (৬GB/১২৮GB)', NULL, 18999, 25999, '📱', NULL, 4.6, 2350, 1241, 'হট', 0, '["কালো", "নীল", "সিলভার"]', NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (2, 'e', 'ওয়্যারলেস ব্লুটুথ হেডফোন (ANC)', NULL, 1299, 2499, '🎧', NULL, 4.4, 1890, 3425, 'ফ্রি ডেলিভারি', 1, '["কালো", "সাদা"]', NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (3, 'e', 'স্মার্ট ওয়াচ T900 (কল সাপোর্ট)', NULL, 999, 2299, '⌚', NULL, 4.3, 2105, 4210, 'ফ্রি ডেলিভারি', 1, '["কালো", "গোল্ড", "সিলভার"]', NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (4, 'e', 'ল্যাপটপ কুলিং প্যাড (৫ ফ্যান)', NULL, 690, 1250, '💻', NULL, 4.2, 540, 870, 'নতুন', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (5, 'e', '২০০০০mAh ফাস্ট পাওয়ার ব্যাংক', NULL, 1450, 2350, '🔋', NULL, 4.5, 1220, 2100, 'ভেরিফায়েড', 1, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (6, 'e', 'মেকানিক্যাল গেমিং কিবোর্ড (RGB)', NULL, 2350, 3800, '⌨️', NULL, 4.6, 860, 760, 'হট', 0, '["কালো", "সাদা"]', NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (7, 'e', 'টু-ইন-ওয়ান ফাস্ট ডেটা ক্যাবল (60W)', NULL, 240, 550, '🔌', NULL, 4.1, 340, 5300, 'ফ্রি ডেলিভারি', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (8, 'e', 'মিনি ব্লুটুথ স্পিকার (ঘন বেস)', NULL, 720, 1400, '🔊', NULL, 4.3, 750, 1150, 'নতুন', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (9, 'f', 'প্রিমিয়াম কটন টি-শার্ট (সব সাইজ)', NULL, 349, 799, '👕', NULL, 4.2, 3200, 8604, 'ফ্রি ডেলিভারি', 1, '["কালো", "সাদা", "নেভি", "লাল"]', '["S", "M", "L", "XL", "XXL"]');
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (10, 'f', 'এমব্রয়ডারি ক্লাসিক পাঞ্জাবি', NULL, 1290, 2400, '👔', NULL, 4.5, 980, 1450, 'হট', 0, '["অফ-হোয়াইট", "মেরুন", "নেভি"]', '["M", "L", "XL", "XXL"]');
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (11, 'f', 'ক্লাসিক লেদার স্নিকার্স', NULL, 1499, 2999, '👟', NULL, 4.4, 1560, 2340, 'ফ্রি ডেলিভারি', 1, '["কালো", "সাদা", "ধূসর"]', '["39", "40", "41", "42", "43", "44"]');
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (12, 'f', 'নকশা করা সালোয়ার কামিজ', NULL, 1150, 2200, '👗', NULL, 4.3, 760, 980, 'নতুন', 0, '["লাল", "নীল", "সবুজ"]', '["M", "L", "XL"]');
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (13, 'f', 'ফ্যাশনেবল সানগ্লাস (UV400)', NULL, 399, 999, '🕶️', NULL, 4.1, 540, 3100, 'ফ্রি ডেলিভারি', 1, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (14, 'f', 'গোল্ড প্লেটেড জুয়েলারি সেট', NULL, 890, 1800, '💍', NULL, 4.4, 640, 1230, 'ভেরিফায়েড', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (15, 'f', 'উইন্টার হুডি জ্যাকেট', NULL, 1350, 2600, '🧥', NULL, 4.5, 890, 760, 'হট', 0, '["ধূসর", "কালো", "নেভি"]', '["M", "L", "XL"]');
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (16, 'f', 'ক্যাজুয়াল কটন ক্যাপ (টুপি)', NULL, 320, 650, '🧢', NULL, 4.2, 430, 1900, 'নতুন', 0, '["কালো", "নেভি", "লাল"]', NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (17, 'h', 'নন-স্টিক ফ্রাই প্যান (২৮ সেমি)', NULL, 899, 1650, '🍳', NULL, 4.4, 1300, 4200, 'ফ্রি ডেলিভারি', 1, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (18, 'h', 'সিরামিক ডিনার সেট (২৪ পিস)', NULL, 2790, 4500, '🍽️', NULL, 4.6, 320, 410, 'ভেরিফায়েড', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (19, 'h', 'LED রিচার্জেবল টেবিল ল্যাম্প', NULL, 749, 1500, '💡', NULL, 4.3, 870, 1350, 'ফ্রি ডেলিভারি', 1, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (20, 'h', 'প্রিন্টেড ডাবল বেডশিট (৩ পিস)', NULL, 1250, 2400, '🛏️', NULL, 4.5, 1500, 2600, 'হট', 0, '["লাল", "নীল", "সবুজ"]', NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (21, 'h', 'এয়ার টাইট স্টোরেজ কনটেইনার (৬ পিস)', NULL, 590, 1100, '🗄️', NULL, 4.2, 680, 1900, 'নতুন', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (22, 'h', 'স্টেইনলেস স্টিল থার্মোফ্লাস্ক', NULL, 480, 950, '🫖', NULL, 4.4, 520, 980, 'ফ্রি ডেলিভারি', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (23, 'b', 'ভিটামিন-C ফেস সিরাম (৩০ মিলি)', NULL, 590, 1200, '✨', NULL, 4.5, 2100, 5600, 'হট', 1, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (24, 'b', 'হায়ালুরনিক ফেস ওয়াশ', NULL, 320, 650, '🧼', NULL, 4.3, 1800, 4100, 'ফ্রি ডেলিভারি', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (25, 'b', 'লং লাস্টিং পারফিউম (১০০ মিলি)', NULL, 850, 1900, '🌸', NULL, 4.4, 940, 2300, 'ভেরিফায়েড', 1, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (26, 'b', 'ম্যাট লিপস্টিক সেট (৫টি)', NULL, 460, 999, '💄', NULL, 4.2, 1300, 3700, 'নতুন', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (27, 'b', 'সানস্ক্রিন SPF 50+ PA+++', NULL, 450, 900, '☀️', NULL, 4.6, 1100, 2900, 'ফ্রি ডেলিভারি', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (28, 'b', 'অ্যালোভেরা হেয়ার অয়েল (২০০ মিলি)', NULL, 280, 550, '🌿', NULL, 4.1, 760, 2100, 'নতুন', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (29, 'g', 'মিনিকেট চাল — প্রিমিয়াম (৫ কেজি)', NULL, 425, 520, '🌾', NULL, 4.4, 3400, 9800, 'ফ্রি ডেলিভারি', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (30, 'g', 'সয়াবিন তেল (৫ লিটার)', NULL, 810, 880, '🛢️', NULL, 4.3, 2600, 7300, 'ভেরিফায়েড', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (31, 'g', 'প্রিমিয়াম চা পাতা (৫০০ গ্রাম)', NULL, 265, 380, '🍵', NULL, 4.5, 1900, 5400, 'ফ্রি ডেলিভারি', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (32, 'g', 'খাঁটি সুন্দরবনের মধু (৫০০ গ্রাম)', NULL, 640, 1200, '🍯', NULL, 4.6, 1500, 4101, 'হট', 1, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (33, 'g', 'ইরানি খেজুর (১ কেজি)', NULL, 480, 750, '🌴', NULL, 4.4, 980, 2600, 'নতুন', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (34, 'g', 'মিক্স ড্রাই ফ্রুটস (৫০০ গ্রাম)', NULL, 590, 950, '🥜', NULL, 4.3, 720, 1900, 'ফ্রি ডেলিভারি', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (35, 't', 'রিমোট কন্ট্রোল রেসিং কার', NULL, 1390, 2500, '🚗', NULL, 4.4, 860, 1900, 'হট', 1, '["লাল", "নীল"]', NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (36, 't', 'সফট টেডি বিয়ার (৬০ সেমি)', NULL, 520, 1100, '🧸', NULL, 4.6, 2100, 4800, 'ফ্রি ডেলিভারি', 1, '["ব্রাউন", "ক্রিম", "পিংক"]', NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (37, 't', 'বেবি ডায়াপার প্যান্ট (M, ৬২ পিস)', NULL, 1150, 1450, '👶', NULL, 4.5, 3200, 8600, 'ভেরিফায়েড', 0, NULL, '["S", "M", "L", "XL"]');
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (38, 't', 'বিল্ডিং ব্লক সেট (১০০ পিস)', NULL, 430, 900, '🧱', NULL, 4.3, 940, 2700, 'নতুন', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (39, 't', 'বার্বি ডল উইথ অ্যাক্সেসরিজ', NULL, 560, 1200, '👸', NULL, 4.2, 1200, 3300, 'ফ্রি ডেলিভারি', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (40, 't', 'কিডস সাইকেল (২০ ইঞ্চি)', NULL, 6900, 9500, '🚲', NULL, 4.5, 210, 340, 'হট', 0, '["লাল", "নীল"]', NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (41, 's', 'ক্রিকেট ব্যাট (কাশ্মীর উইলো)', NULL, 1850, 3200, '🏏', NULL, 4.5, 760, 1400, 'ভেরিফায়েড', 0, NULL, '["SH", "H", "LH"]');
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (42, 's', 'ফুটবল ম্যাচ বল (সাইজ ৫)', NULL, 890, 1600, '⚽', NULL, 4.4, 1300, 3600, 'ফ্রি ডেলিভারি', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (43, 's', 'অ্যাডজাস্টেবল ডাম্বেল সেট (১০ কেজি)', NULL, 2450, 4000, '🏋️', NULL, 4.3, 540, 890, 'নতুন', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (44, 's', 'অ্যান্টি-স্লিপ যোগা ম্যাট', NULL, 690, 1400, '🧘', NULL, 4.5, 1100, 2400, 'ফ্রি ডেলিভারি', 1, '["বেগুনি", "নীল", "সবুজ"]', NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (45, 's', 'ব্যাডমিন্টন র‍্যাকেট সেট (২টি)', NULL, 980, 1900, '🏸', NULL, 4.2, 870, 2100, 'হট', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (46, 's', 'ফিটনেস স্কিপিং রোপ', NULL, 220, 480, '🪢', NULL, 4.4, 1500, 5100, 'ফ্রি ডেলিভারি', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (47, 'k', 'ল্যাপটপ/অফিস ব্যাকপ্যাক (ওয়াটারপ্রুফ)', NULL, 1150, 2200, '🎒', NULL, 4.5, 2300, 6100, 'হট', 1, '["কালো", "ধূসর", "নেভি"]', NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (48, 'k', 'প্রিমিয়াম ডায়েরি ও পেন গিফট সেট', NULL, 240, 520, '📓', NULL, 4.3, 760, 2200, 'নতুন', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (49, 'k', 'বলপয়েন্ট পেন (১০ পিস, জার্মান ইঙ্ক)', NULL, 150, 300, '🖊️', NULL, 4.2, 1900, 8600, 'ফ্রি ডেলিভারি', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (50, 'k', 'ডেস্কটপ সায়েন্টিফিক ক্যালকুলেটর', NULL, 560, 1100, '🧮', NULL, 4.4, 640, 1500, 'ভেরিফায়েড', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (51, 'k', 'বাংলা উপন্যাস সংকলন (৫টি বই)', NULL, 750, 1500, '📚', NULL, 4.6, 890, 1800, 'নতুন', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (52, 'k', 'আর্ট ড্রয়িং সেট (৮৩ পিস)', NULL, 690, 1350, '🎨', NULL, 4.4, 1200, 2900, 'ফ্রি ডেলিভারি', 0, NULL, NULL);
INSERT INTO products (id, cat, name, name_en, price, old, e, img, r, rv, sold, tag, f, colors, sizes) VALUES (53, 'e', 'হ্যান্ডলুম শাড়ি (লাল)', NULL, 1250, 2400, '🧣', NULL, 4.5, 1, 0, 'নতুন', 0, NULL, NULL);

DELETE FROM settings;
INSERT INTO settings (id, phone, whatsapp, telegram, facebook, email, bkash, nagad, rocket, cod) VALUES (1, '01717877955', '8801717877955', '8801717877955', 'https://www.facebook.com/share/19KVN4rZkS/', 'tnextgen04@gmail.com', '01717877955', '01717877955', '01717877955', 1);
